### ISSUE TITLE
fetch info about all open GitHub issues with one of the configured labels assigned to it

### ISSUE THREAD

**Issue by ivanammm** [WomenWhoCode/berlin-issues-explorer-be#2]
Configure list of labels suitable for beginners and fetch from GitHub API all issues with one of those labels assigned to it. 

Labels include but are not limited to: `first-timers-only`, `up-for-grabs`, `newcomer`,  `good first issue`, `jump-in`, `beginner friendly`. To be researched if there are more labels pointing to issues suitable for people who haven't contributed to open source yet.

About every issue store issue title, labels, repository title and language.

For the beginning, data should be stored in memory (limited set in case amount of issues is too big, purpose of this task is to implement functionality to fetch data).

**Comment by zassmin** [comment]
"beginner friendly" is another one commonly used

**Comment by annaira** [comment]
Use Request Key From Environment Variable
